### ISSUE TITLE
Do not include modules disabled in D7 into list of downloadable modules

### ISSUE THREAD

**Issue by irinaz** [backdrop-contrib/d2b_migrate#32]
In step "Database Analysis" do not include modules that are disabled in D7 into list of downloadable projects, only modules that are enabled in D7.   Often sites have many modules that have been disabled, including custom or outdated modules, and listing them in the new Backdrop site creates clutter. 

https://github.com/backdrop-contrib/d2b_migrate/blob/1.x-1.x/d2b_migrate.module#L580

**Comment by docwilmot** [comment]
Or maybe include them but uncheck the checkbox and/or add a "disabled in source" notification or icon?

**Comment by irinaz** [comment]
Uncheck by default and "disabled in source" in the column where we show "in core/downloaded/available/ not ported yet) will work well.  It allows to show information about old system without actually downloading.   For example, we are using D7 distribution with 304 module of which 118 are disabled.

**Comment by irinaz** [comment]
I tested module and it is still downloading projects that were unchecked

**Comment by docwilmot** [comment]
This should be fixed

**Comment by irinaz** [comment]
I still see modules that are disabled in the D7 source website in the list of modules on the new backdrop site.

**Comment by docwilmot** [comment]
I dont understand what you mean. When you click "Download available projects" does D2B download unchecked modules?

**Comment by irinaz** [comment]
My intent here was to check if a module is enabled in D7, and not include it into list if it is disabled.  For example, in one of my demo projects Biblio module is disabled, but it shows up in the list of modules available for download.  Let me know if this explains my request better.  Thank you so much for working on this module!!

**D7 list of modules**
<img width="1173" alt="Screenshot 2023-12-27 at 8 03 48 AM" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/78373203-d6d7-4755-9707-b33bdb72bbb1">

**Backdrop database analysis**
<img width="1301" alt="Screenshot 2023-12-27 at 8 04 00 AM" src="https://github.com/backdrop-contrib/d2b_migrate/assets/2497005/b3fc2639-6721-475c-a2f9-cb10fc1949f2">

**Comment by docwilmot** [comment]
Please recall [this conversation](https://github.com/backdrop-contrib/d2b_migrate/issues/32#issuecomment-1837760915) which was implemented in the last commit.

![Screenshot 2023-12-27 115301](https://github.com/backdrop-contrib/d2b_migrate/assets/1042283/402738cf-5f50-4f63-b012-90032d513162)

**Comment by irinaz** [comment]
@docwilmot , thank you for reminding me about https://github.com/backdrop-contrib/d2b_migrate/issues/32#issuecomment-1837652285 and adding a screenshot here with new implementation.   I will double check that "biblio" module quoted in my comment is not checked and I can see (_Disabled in source_) text.

**Comment by irinaz** [comment]
@docwilmot, I created new site, downloaded most recent version of d2b module, connected to D7 database, and I do not see "(Disabled in source)".  I changed line 483 to the following and this way modules are showing in the list exactly as described in #32.  Let me know  if I should file PR or you can update code directly.   Thank you so much for making it all work!
`    if ( $project['project_status'] == 0) {`

**Comment by docwilmot** [comment]
Was a PHP version issue I think. I had version 7.4 local and indeed it didnt work when I switched to version 8.2. Fixed now I believe. Please try again.

**Comment by mue368** [comment]
Heute habe ich versucht mit der neuesten Backdrop und d2b_migrate Version meine bereinigte Drupal 7 Version zu migrieren. Ich habe also bereist vorher alle Module, die in Backdrop nicht mehr verfügbar sind, deaktiviert UND desinstalliert. Dann habe ich eine neue Backdrop Installation in der Sprache Deutsch durchgeführt, in der Backdrop Konfiguration die Pfade für das private Dateisystem angegeben, alle notwendigen Backdrop Module per Hand in den Backdrop Pfad "modules" heruntergeladen und die Dateien aus dem öffentlichen Dateisystem der alten Drupal Installation nach Backdrop kopiert. Dies entspricht exakt dem Vorgehen beim Standardverfahren des Backdrop Upgrades. Ich verwende auf meinem Entwicklungsserver die PHP Version 8.1.  Im 2. Schritt "Source analysis" des Moduls d2b_migrate wird oben davon gesprochen das nach dem Klick auf "UPDATE PROJECT DATA" für jedes gefundene Modul Checkboxen sichtbar sein müssten. Dies ist aber bei mir nicht der Fall. Es gibt keinerlei Auswahlmöglichkeit:
![Screenshot 2023-12-30 133003](https://github.com/backdrop-contrib/d2b_migrate/assets/58108879/7986ec2c-4911-400d-a1a4-83dbfe30bb29)
Falls es also ein Problem mit der PHP Version geben sollte so ist dies leider nicht behoben.
Vielen Dank.

**Comment by mue368** [comment]
Today I tried to migrate my clean Drupal 7 version with the latest Backdrop and d2b_migrate version. I have already deactivated AND uninstalled all modules that are no longer available in Backdrop. Then I performed a new Backdrop installation in the German language, specified the paths for the private file system in the Backdrop configuration, manually downloaded all necessary Backdrop modules to the Backdrop path "modules" and copied the files from the public file system of the old Drupal installation to Backdrop. This is exactly the same as the standard Backdrop upgrade procedure. I use PHP version 8.1 on my development server. In the 2nd step "Source analysis" of the module d2b_migrate it is mentioned above that after clicking on "UPDATE PROJECT DATA" checkboxes should be visible for each module found. However, this is not the case for me. There is no selection option at all:
![Screenshot 2023-12-30 133003](https://github.com/backdrop-contrib/d2b_migrate/assets/58108879/9d3eb01d-552e-4945-b4d5-8c703bb1f397)
So if there is a problem with the PHP version, this is unfortunately not fixed.
Thank you very much.

**Comment by docwilmot** [comment]
This is strange. I cannot understand why the checkboxes would not show. Are there any errors in your logs? Javascript errors? The `tableselect` code is not conditional in any way, it shouldnt disappear.

**Comment by mue368** [comment]
It does not seem to be due to the PHP version. I temporarily reverted to version 7.4.26 and the error persisted. Of course, I also deleted all caches several times in between and ran update.php. No errors were displayed. In the meantime I have unfortunately deleted the DB again and am trying another standard update. Unfortunately, there are always errors so that you need several attempts. The errors look like this:
![Screenshot 2023-12-30 144511](https://github.com/backdrop-contrib/d2b_migrate/assets/58108879/02c2a43e-e3bc-41fd-9ac7-7ea1ac31031d)

**Comment by docwilmot** [comment]
We expect errors, but the image in https://github.com/backdrop-contrib/d2b_migrate/issues/32#issuecomment-1872387384 is unexpected. Is the sidebar task list missing too? Can you show the whole page?

**Comment by mue368** [comment]
I have now reinstalled everything with PHP version 7.24 and English language. I have also left the default download method as standard:
![Screenshot 2023-12-30 152335](https://github.com/backdrop-contrib/d2b_migrate/assets/58108879/407ba0d7-a285-4b7b-ae49-6fd993582c8b)
I have activated the output of ALL messages. When I call up the Source analysis step, I get the following output:
![Screenshot 2023-12-30 151759](https://github.com/backdrop-contrib/d2b_migrate/assets/58108879/b57e84b3-a261-47bc-a488-fc9ccfa45682)
The note on the empty Port field is certainly irrelevant. As I use the standard port, nothing needs to be entered there. 
The checkboxes are still not visible. There is also no entry in the source code:
![Screenshot 2023-12-30 153056](https://github.com/backdrop-contrib/d2b_migrate/assets/58108879/892d5fb0-3d86-4ab7-b548-cf42cbd7dea4)

**Comment by yorkshire-pudding** [comment]
I've tested the latest version and I now get the checkboxes unchecked and with the suffix "(Disabled in source)"

**Comment by docwilmot** [comment]
@mue368 are you using the latest version from GitHub?

Edit: no you're not! Just realized your UI is the very old version. The new changes are not released yet sorry.

**Comment by irinaz** [comment]
@docwilmot, @quicksketch  , I think that it is definitely worth doing new release with the new code, even if there are some minor bugs.  It would be such an amazing achievement in 2023!!!  Thank you so much !

**Comment by docwilmot** [comment]
Thanks @irinaz. We'd need comments on the issue queues specifying which issues are resolved and which still have bugs before we release. We need testing in other words.

**Comment by irinaz** [comment]
This is issue has been tested, and is ready for release.
